### ISSUE TITLE
你好，我现在在做云旺的android集成，有几个问题想向您咨询一下

### ISSUE THREAD

**Issue by zxzfcsu** [loonslo/IMCore_Demo#1]
您的源码我下载了，但是无法运行，所以我看了您的源码，主要向您请教几个问题，谢谢：

1.您的程序运行起来类似与云旺自己的demo吗？您的联系人界面能够实现吗？
2.我自己按照他们官网上的教程试了一下，联系人界面出来之后页面不全，上方的toolbar和他的demo不同；
3.我试了一下他的contactService.addContact方法和contactService.delContact方法，都返回error

**Comment by loonslo** [comment]
我这个是不能实现的，我用的是IMCORE库。如果你只是想实现，他们官网的页面，可以直接使用IMkit库，（IMKIT高度封装了IMCORE）。
打开消息列表，使用这个方法就可以了,getConversationActivityIntent()

**Comment by zxzfcsu** [comment]
好的，消息
